M48
; DRILL file {KiCad (6.0.0)} date Thu Feb 24 22:11:58 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-24T22:11:58+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X3.6154Y-1.5303
X3.6154Y-3.8138
X4.5209Y-1.5303
X4.5209Y-3.8138
T0
M30
